module de.vsy.chat.server.test{
    requires org.junit.jupiter.api;
    requires de.vsy.chat.shared_transmission;
    requires de.vsy.chat.shared_utility;
    requires de.vsy.chat.server;
    requires com.fasterxml.jackson.databind;
    requires org.apache.logging.log4j;
    requires de.vsy.chat.shared_module;
    opens de.vsy.chat.server.raw_server_test;
    opens de.vsy.chat.server.raw_server_test.authentication;
    opens de.vsy.chat.server.raw_server_test.chat;
    opens de.vsy.chat.server.raw_server_test.relation;
    opens de.vsy.chat.server.raw_server_test.status;
    exports de.vsy.chat.server.single_server_test.authentication;
    exports de.vsy.chat.server.single_server_test.chat;
    exports de.vsy.chat.server.single_server_test.relation;
    exports de.vsy.chat.server.single_server_test.status;
    exports de.vsy.chat.server.two_server_test.authentication;
    exports de.vsy.chat.server.two_server_test.chat;
    exports de.vsy.chat.server.two_server_test.relation;
    exports de.vsy.chat.server.two_server_test.status;
}